version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - redis

  blog-service:
    build: ./blog-service
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - blog-db
      - redis

  image-service:
    build: ./image-service
    ports:
      - "5002:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - redis

  blog-db:
    image: postgres:13
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  unittest-service:
    build:
      context: ./unittest-service
      dockerfile: Dockerfile
    depends_on:
      - auth-service
      - blog-service
      - image-service
      - blog-db
      - redis
    environment:
      - FLASK_APP=app
      - FLASK_ENV=testing
